jenkins:
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "OperationsCenter2"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  numExecutors: 0
unclassified:
  artifactManager:
    artifactManagerFactories:
      - jclouds:
          provider: s3
  globallibraries:
    libraries:
    - defaultVersion: "completed"
      name: "cd-accel"
      retriever:
        modernSCM:
          scm:
            github:
              credentialsId: "cd-accel-github-token"
              repoOwner: "cloudbees-cd-acceleration-workshop"
              repository: "pipeline-library"
aws:
  s3:
    container: "cd-accel"
    prefix: "cb-core/artifacts/"