jenkins:
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "OperationsCenter2"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  numExecutors: 0
unclassified:
  artifactManager:
    artifactManagerFactories:
      - jclouds:
          provider: s3
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "kypseli"
      retriever:
        modernSCM:
          scm:
            github:
              credentialsId: "kypseli-github-token"
              repoOwner: "kypseli"
              repository: "pipeline-library"
  slackNotifier:
    teamDomain: beedemo-team
    tokenCredentialId: beedemo-slack
    room: "#ci"
aws:
  s3:
    container: "cd-accel"
    prefix: "cb-core/artifacts/"